### ISSUE TITLE
Annotate namespaces with the Gateway for ingress traffic

### ISSUE THREAD

**Issue by israel-hdez** [maistra/odh-project-controller#12]
For ModelMesh there is the need to expose InferenceServices. The controller managing this is [`odh-model-controller`](https://github.com/opendatahub-io/odh-model-controller/).

For the Istio integration, the `odh-model-controller` is going to create VirtualServices. A gateway needs to be specified in such VirtualServices to properly expose models. Since the `odh-project-controller` has this knowledge, it is going to be very useful to have ~~labels~~ annotations over the namespaces to set the Gateway namespace/name that can be used for exposing models.

Suggested ~~labels~~ annotations are the ones already in use in the route: `maistra.io/gateway-name` and `maistra.io/gateway-namespace`.

**Comment by israel-hdez** [comment]
@bartoszmajsak I agree that using `annotations` is better for this.

Also, using `opendatahub.io/serive-mesh-gateway-name` makes more sense than using `maistra` in the prefix, given that this would be out of the maistra domain. Would it be a single annotation? Or a pair for namespace and gateway name?

**Comment by bartoszmajsak** [comment]
@israel-hdez Please take a look https://github.com/maistra/odh-project-controller/pull/13

**Comment by bartoszmajsak** [comment]
@israel-hdez this is now pushed to `maistra-dev` repo, you can find it here: quay.io/maistra-dev/odh-project-controller
